name: Teleauro-Dev-Build

on:
  push:
    branches: [ develop ]

jobs:

  Teleauro-Maven-Build:
    name: Teleauro Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn clean install -DskipTests
      - run: mkdir output && cp -R authentication datamanagement output
      - uses: actions/upload-artifact@v4
        with:
          name: Output
          path: output

  Teleauro-Authentication-Build:
    name: Teleauro Authentication Build
    needs: [ Teleauro-Maven-Build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: Output

      - name: Build docker image
        run: docker build -f authentication/Dockerfile -t teleauro-sales-app-authentication .

      - name: Stop and remove container
        continue-on-error: true
        run: docker stop authentication && docker rm authentication

      - name: Run container
        run: docker run -d -p 8083:9090 --name authentication teleauro-sales-app-authentication

  Teleauro-DataManagement-Build:
    name: Teleauro Data Management Build
    needs: [ Teleauro-Maven-Build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: Output

      - name: Build docker image
        run: docker build -f datamanagement/Dockerfile -t teleauro-sales-app-datamanagement .

      - name: Stop and remove container
        continue-on-error: true
        run: docker stop datamanagement && docker rm datamanagement

      - name: Run container
        run: docker run -d -p 8083:9090 --name datamanagement teleauro-sales-app-datamanagement
  
  Teleauro-Delete-Artifact:
    name: Teleauro Delete Artifact
    needs: [ Teleauro-Authentication-Build, Teleauro-DataManagement-Build ]
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: Output
